[package]
name = "kyori-rs"
version = "0.1.0"
edition = "2021"
description = "a small library for calculating the distance of two coordinates on earth"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
